name: 🚀 Publish and release

on:
  push:
    tags:
      - v*

jobs:
  publish-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 🔃 Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 🛠️ Install and build
        run: npm i

      - name: 🧹 Delete extra files
        run: |
          rm -rf node_modules src .github
          rm .gitignore package.json package-lock.json webpack.config.js

      - name: 📢 Publish sample
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true

      - name: 🔖 Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
