name: Build and publish sample
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and build 🔧
        run: |
          npm ci
          npm run build

      - name: Delete extra files ❌
        run: |
          rm -rf node_modules src .github
          rm .gitignore package.json package-lock.json webpack.config.js

      - name: Publish sample 📢
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
