name: 🚀 Publish and release

on:
  push:
    tags:
      - v*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 🛠️ Install and build
        run: npm i

      - name: 🧹 Delete extra files
        run: |
          rm -rf node_modules src .github
          rm .gitignore package.json package-lock.json webpack.config.js

      - name: 📢 Publish sample
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true

  create-release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: 🔃 Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: 🛎️ Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
